language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t danielpo/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true danielpo/docker-react npm run test
#  - docker run danielpo/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-373619255624"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
