FROM node:alpine

WORKDIR '/app'

COPY package.json .

#ENV http_proxy="http://stlwbsproxy.corp.amdocs.com:8080"
#ENV https_proxy="http://stlwbsproxy.corp.amdocs.com:8080"
RUN npm install

COPY . .

CMD ["npm", "run", "start"]
